services:
  - type: web
    name: kamasutra-backend
    runtime: node
    repo: https://github.com/x-xxplro/Kamasutra
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATA_DIR
        value: ./backend/data  